AWSTemplateFormatVersion: 2010-09-09
Description: Template for static s3 website

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Versioning:
    Description: Is versioning enabled
    Type: String
    AllowedValues:
      - 'true'
      - 'false'

Conditions:
  IsVersioningEnabled: !Equals [!Ref Versioning, 'true']

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration: !If
        - IsVersioningEnabled
        - Status: Enabled
        - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-artifact-bucket

  ArtifactBucketNameParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: String
      Description: !Sub Stores ${Project} ${Stage} Artifact bucket name
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/artifact-bucket/bucket-name
      Value: !Ref ArtifactBucket
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-artifact-bucket-name-param

Outputs:
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
  ArtifactBucketNameParamName:
    Value: !Ref ArtifactBucketNameParam