AWSTemplateFormatVersion: 2010-09-09
Description: Template for log bucket

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$

Resources:
  S3LogBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl:  LogDeliveryWrite
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-log-bucket

Outputs:
  LogBucketName:
    Value: !Ref S3LogBucket
    Description: S3 Log Bucket Name
