AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$

Resources:
  LogBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log-bucket.yaml
      Parameters:
        Project: !Ref Project
        Component: !Ref Component
        Stage: !Ref Stage

  Website:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: website.yaml
      Parameters:
        Project: !Ref Project
        Component: !Ref Component
        Stage: !Ref Stage
        LogBucketName: !GetAtt LogBucket.Outputs.LogBucketName