AWSTemplateFormatVersion: 2010-09-09
Description: Network template for NAT Gateway

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  PublicSubnet:
    Description: Reference of the PublicSubnet from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  PrivateRouteTable:
    Description: Reference of the PrivateRouteTable from the SSM
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  NatGatewayEIP:
      Type: AWS::EC2::EIP
      Properties:
        Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-nat-gateway

  DefaultPrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

Outputs:
  NatGatewayId:
    Description: Nat Gateway Id
    Value: !Ref NatGateway
  NatGatewayEIP:
    Description: Nat Gateway EIP
    Value: !Ref NatGatewayEIP
