AWSTemplateFormatVersion: 2010-09-09
Description: Network template for  VPC

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  DataSubnetACidr:
    Description: Data Subnet A CIDR
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Type: String
  DataSubnetBCidr:
    Description: Data Subnet B CIDR
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Type: String
  PublicSubnetACidr:
    Description: Public Subnet A CIDR
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Type: String
  PublicSubnetBCidr:
    Description: Public Subnet B CIDR
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Type: String
  PrivateSubnetACidr:
    Description: Subnet A Cidr
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Type: String
  PrivateSubnetBCidr:
    Description: Subnet B Cidr
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Type: String
  VpcCidrBlock:
    Type: String
    Description: CIDR block for the VPC
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
  LogBucketArn:
    Description: Log bucket form SSM Parameter
    Type: AWS::SSM::Parameter::Value<String>
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-vpc

  VpcIdParam:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: !Sub Stores ${Project}-${Stage}-${Component} Vpc ID
        Tier: Standard
        Name: !Sub /${Project}/${Stage}/${Component}/vpc/vpc-id
        Value: !Ref Vpc
        Tags:
          Name: !Sub ${Project}-${Stage}-${Component}-vpc-id

  FlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      LogDestination: !Sub ${LogBucketArn}/vpc-flow-logs/vpc/
      LogDestinationType: s3
      ResourceId: !Ref Vpc
      ResourceType: VPC
      TrafficType: ALL

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0 , !GetAZs '' ]
      VpcId: !Ref Vpc
      CidrBlock: !Ref PublicSubnetACidr
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-public-subnet-a

  PublicSubnetAIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component}- PublicSubnetA Id
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/public-subnet-a/subnet-id
      Value: !Ref PublicSubnetA
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-public-subnet-a-id

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1 , !GetAZs '' ]
      VpcId: !Ref Vpc
      CidrBlock: !Ref PublicSubnetBCidr
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-public-subnet-b

  PublicSubnetBIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component}- PublicSubnetB  Id
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/public-subnet-b/subnet-id
      Value: !Ref PublicSubnetB
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-public-subnet-b-id

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0 , !GetAZs '' ]
      VpcId: !Ref Vpc
      CidrBlock: !Ref PrivateSubnetACidr
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-private-subnet-a

  PrivateSubnetAIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component}- PrivateSubnetA Id
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/private-subnet-a/subnet-id
      Value: !Ref PrivateSubnetA
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-private-subnet-a-id

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1 , !GetAZs '' ]
      VpcId: !Ref Vpc
      CidrBlock: !Ref PrivateSubnetBCidr
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-private-subnet-b

  PrivateSubnetBIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component}- PrivateSubnetB  Id
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/private-subnet-b/subnet-id
      Value: !Ref PrivateSubnetB
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-private-subnet-b-id

  DataSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0 , !GetAZs '' ]
      VpcId: !Ref Vpc
      CidrBlock: !Ref DataSubnetACidr
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-data-subnet-a

  DataSubnetAIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component}- DataSubnetA Id
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/data-subnet-a/subnet-id
      Value: !Ref DataSubnetA
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-data-subnet-a-id

  DataSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1 , !GetAZs '' ]
      VpcId: !Ref Vpc
      CidrBlock: !Ref DataSubnetBCidr
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-data-subnet-b

  DataSubnetBIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component}- DataSubnetB  Id
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/data-subnet-b/subnet-id
      Value: !Ref DataSubnetB
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-data-subnet-b-id

  InternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: !Sub ${Project}-${Stage}-${Component}-internet-gateway

  AttachGateway:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId: !Ref Vpc
        InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-public-route-table

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicRouteTableIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component} PublicRouteTableID
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/public-route-table/rt-id
      Value: !Ref PublicRouteTable
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-public-route-table-id

  PublicSubnetARouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref PublicRouteTable
        SubnetId: !Ref PublicSubnetA

  PublicSubnetBRouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref PublicRouteTable
        SubnetId: !Ref PublicSubnetB

  PrivateRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableA
      SubnetId: !Ref PrivateSubnetA

  PrivateRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTableB
      SubnetId: !Ref PrivateSubnetB

  DataRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref DataRouteTableA
      SubnetId: !Ref DataSubnetA

  DataRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref DataRouteTableB
      SubnetId: !Ref DataSubnetB

  PrivateRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-private-route-table-a

  PrivateRouteTableAIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component} Private Route Table A ID
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/private-route-table-a/rt-id
      Value: !Ref PrivateRouteTableA
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-private-route-table-a-id

  PrivateRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-private-route-table-b

  PrivateRouteTableBIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component} Private Route Table B ID
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/private-route-table-b/rt-id
      Value: !Ref PrivateRouteTableB
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-private-route-table-b-id

  DataRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-data-route-table-a

  DataRouteTableAIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component} Data Route Table A ID
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/data-route-table-a/rt-id
      Value: !Ref DataRouteTableA
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-data-route-table-a-id

  DataRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-data-route-table-b

  DataRouteTableBIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component} Data Route Table B ID
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/data-route-table-b/rt-id
      Value: !Ref DataRouteTableB
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-data-route-table-b-id

Outputs:
  VpcId:
    Description: The ID of  VPC
    Value: !Ref Vpc
  VpcIdParamName:
    Description: The name of the SSM parameter where the Id of the  VPC is stored
    Value: !Ref VpcIdParam
  PrivateSubnetAId:
    Description: The ID of private subnet A
    Value: !Ref PrivateSubnetA
  PrivateSubnetAIdParamName:
    Description: The name of the SSM parameter where the Id of the private subnet A is stored
    Value: !Ref PrivateSubnetAIdParam
  PrivateSubnetBId:
    Description: The ID of private subnet B
    Value: !Ref PrivateSubnetB
  PrivateSubnetBIdParamName:
    Description: The name of the SSM parameter where the Id of the private subnet B is stored
    Value: !Ref PrivateSubnetBIdParam
  PublicSubnetAId:
    Description: The ID of public subnet A
    Value: !Ref PublicSubnetA
  PublicSubnetAIdParamName:
    Description: The name of the SSM parameter where the Id of the public subnet A is stored
    Value: PublicSubnetAIdParam
  PublicSubnetBId:
    Description: The ID of public subnet B
    Value: !Ref PublicSubnetB
  PublicSubnetBIdParamName:
    Description: The name of the SSM parameter where the Id of the public subnet B is stored
    Value: PublicSubnetBIdParam
  PrivateRouteTableAId:
    Description: The ID of private route table A
    Value: !Ref PrivateRouteTableA
  PrivateRouteTableAIdParamName:
    Description: The name of the SSM parameter where the Id of private route table A is stored
    Value: !Ref PrivateRouteTableAIdParam
  PrivateRouteTableBId:
    Description: The ID of private route table B
    Value: !Ref PrivateRouteTableB
  PrivateRouteTableBIdParamName:
    Description: The name of the SSM parameter where the Id of private route table B is stored
    Value: !Ref PrivateRouteTableBIdParam
  DataRouteTableAId:
    Description: The ID of data route table A
    Value: !Ref DataRouteTableA
  DataRouteTableAIdParamName:
    Description: The name of the SSM parameter where the Id of data route table A is stored
    Value: !Ref DataRouteTableAIdParam
  DataRouteTableBId:
    Description: The ID of data route table B
    Value: !Ref DataRouteTableB
  DataRouteTableBIdParamName:
    Description: The name of the SSM parameter where the Id of data route table B is stored
    Value: !Ref DataRouteTableBIdParam
  PublicRouteTableId:
    Description: The ID the the public route table
    Value: !Ref PublicRouteTable
  PublicRouteTableIdParamName:
    Description: The name of the SSM parameter where the Id of the public route table is stored
    Value: !Ref PublicRouteTableIdParam
