AWSTemplateFormatVersion: 2010-09-09
Description: Template for AWS CloudFront CDN

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  AlbUrl:
    Description: Url of Load Balancer which serves backend of the application
    Type: AWS::SSM::Parameter::Value<String>
  S3WebsiteBucketName:
    Description: Name of bucket which stores static frontend website
    Type: AWS::SSM::Parameter::Value<String>
  # WAF: # This should be commented out if WAF is not used at all
  #   Description: Web ACL ID for use with the distribution
  #   Type: AWS::SSM::Parameter::Value<String>

Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 400
          - ErrorCachingMinTTL: 1
            ErrorCode: 403
          - ErrorCachingMinTTL: 5
            ErrorCode: 500
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 86400
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: true
            QueryStringCacheKeys:
              - _cftp
            Headers:
              - Access-Control-Request-Headers
              - Access-Control-Request-Method
              - Origin
              - Authorization
              - X-AUTH-TOKEN
              - Vary
            Cookies:
              Forward: all
          Compress: true
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: http2
        Origins:
          - Id: AlbOrigin
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
            DomainName: !Ref AlbUrl
            OriginPath: ''
          - Id: S3Origin
            DomainName: !Sub '${S3WebsiteBucketName}.s3.amazonaws.com'
            OriginPath: ''
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessIdentity}'
        CacheBehaviors:
          - TargetOriginId: AlbOrigin
            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0
            ViewerProtocolPolicy: redirect-to-https
            PathPattern: '/memes*'
            ForwardedValues:
              QueryString: true
            AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          - TargetOriginId: AlbOrigin
            MinTTL: 500
            ViewerProtocolPolicy: redirect-to-https
            PathPattern: '/download/*'
            ForwardedValues:
              QueryString: true
#        WebACLId: !Ref WAF # This should be commented out if WAF is not used with AWS CloudFront
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-cdn

  S3BucketPolicyWithAOI:
    Properties:
      Bucket: !Ref S3WebsiteBucketName
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: 'Allow'
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub 'arn:aws:s3:::${S3WebsiteBucketName}/*'
    Type: AWS::S3::BucketPolicy

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access S3 bucket content only through CloudFront

Outputs:
  DistributionId:
    Description: CloudFront distribution ID
    Value: !Ref Distribution
