AWSTemplateFormatVersion: 2010-09-09
Description: Template for git repository

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  SharedStage:
    Description: Stage name for shared resources
    Type: String
    AllowedValues:
      - shared-dev
      - shared-test
      - shared
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Type:
    Description: Repository type
    Type: String
    # AllowedValues:
    #   - automation
    #   - application
    #   - backend
    #   - frontend
    #   - infra
    #   - params
    #   - cicd
    #   - iam

Resources:
  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: !Sub Repository for ${Project} ${Type}
      RepositoryName: !Sub ${Project}-${SharedStage}-${Component}-${Type}
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${SharedStage}-${Component}-${Type}-repository

  RepositoryNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type:  String
      Name: !Sub /${Project}/${SharedStage}/${Component}/repository-${Type}/name
      Value: !GetAtt Repository.Name
      Description: Stores the name of the deployment role in the test account
      Tags:
        Name: !Sub ${Project}-${SharedStage}-${Component}-repository-${Type}-name

Outputs:
  CloneUrlHttp:
    Description: URL for cloning repo using HTTPS
    Value: !GetAtt Repository.CloneUrlHttp
  CloneUrlSsh:
    Description: URL for cloning repo using SSH
    Value: !GetAtt Repository.CloneUrlSsh
  RepositoryNameParamName:
    Description: SSM parameter that stores the repository name
    Value: !Ref RepositoryNameParam
