AWSTemplateFormatVersion: 2010-09-09
Description: Template for alerts

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  ApplicationAlertsTopic:
    Description: ARN of SNS topic for application notifications - alerts
    Type: AWS::SSM::Parameter::Value<String>
  ApplicationInformationTopic:
    Description: ARN of SNS topic for application notifications - info
    Type: AWS::SSM::Parameter::Value<String>
  ApplicationAutoScalingGroup:
    Description: Auto Scaling Group Name
    Type: AWS::SSM::Parameter::Value<String>
  DbIdentifierName:
    Description: Database Instance Name
    Type: AWS::SSM::Parameter::Value<String>
  InfrastructureAlertsTopics:
    Description: ARN of SNS topic for infrastructure notifications - alerts
    Type: AWS::SSM::Parameter::Value<String>
  InfrastructureInformationTopic:
    Description: ARN of SNS topic for infrastructure notifications - info
    Type: AWS::SSM::Parameter::Value<String>
  LoadBalancerFullName:
    Description: Load Balancer Full Name
    Type: AWS::SSM::Parameter::Value<String>
  Period:
    Description: Period in seconds - should be a multiple of 60
    Type: Number

Resources:
  DatabaseDiskUsageAlarmTier1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database Instance Disk usage Tier 1
      AlarmName: !Sub ${Project}-${Stage}-${Component}-db-disk-usage-alarm-tier-1
      ComparisonOperator: LessThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: !Ref Period
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DbIdentifierName
      Threshold: 3
      Statistic: Maximum
      AlarmActions:
      - !Ref InfrastructureInformationTopic

  DatabaseDiskUsageAlarmTier2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database Disk usage Tier 2
      AlarmName: !Sub ${Project}-${Stage}-${Component}-db-disk-usage-alarm-tier-2
      ComparisonOperator: LessThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: !Ref Period
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DbIdentifierName
      Threshold: 2
      Statistic: Maximum
      AlarmActions:
      - !Ref InfrastructureInformationTopic

  DatabaseDiskUsageAlarmTier3:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database Disk usage Tier 3
      AlarmName: !Sub ${Project}-${Stage}-${Component}-db-disk-usage-alarm-tier-3
      ComparisonOperator: LessThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: !Ref Period
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DbIdentifierName
      Threshold: 1
      Statistic: Maximum
      AlarmActions:
      - !Ref InfrastructureAlertsTopics

  DatabaseCPUUsageAlarmTier1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database CPU usage Tier 1
      AlarmName: !Sub ${Project}-${Stage}-${Component}-db-cpu-usage-alarm-tier-1
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      Period: !Ref Period
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DbIdentifierName
      Threshold: 70
      Statistic: Average
      AlarmActions:
      - !Ref InfrastructureInformationTopic

  DatabaseCPUUsageAlarmTier2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database CPU usage Tier 2
      AlarmName: !Sub ${Project}-${Stage}-${Component}-db-cpu-usage-alarm-tier-2
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      Period: !Ref Period
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DbIdentifierName
      Threshold: 80
      Statistic: Average
      AlarmActions:
      - !Ref InfrastructureInformationTopic

  DatabaseCPUUsageAlarmTier3:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database CPU usage Tier 3
      AlarmName: !Sub ${Project}-${Stage}-${Component}-db-cpu-usage-alarm-tier-3
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      Period: !Ref Period
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DbIdentifierName
      Threshold: 90
      Statistic: Average
      AlarmActions:
      - !Ref InfrastructureAlertsTopics

  DatabaseActiveMemoryMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: !Sub '{($.instanceID= "memes-generator-${Stage}-data-db" ) && ($.memory.active = *)}'
      LogGroupName: RDSOSMetrics
      MetricTransformations:
        - MetricValue: '$.memory.active'
          MetricNamespace: "Application/MemesGenerator/DB"
          MetricName: "ActiveDbMemory"

  DatabaseTotalMemoryMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: !Sub '{($.instanceID= "memes-generator-${Stage}-data-db" ) && ($.memory.total = *)}'
      LogGroupName: RDSOSMetrics
      MetricTransformations:
        - MetricValue: '$.memory.total'
          MetricNamespace: "Application/MemesGenerator/DB"
          MetricName: "TotalDbMemory"

  DatabaseMemoryUsageAlarmTier1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database Memory usage Tier 1
      AlarmName: !Sub ${Project}-${Stage}-${Component}-db-mem-usage-alarm-tier-1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Threshold: 70
      Metrics:
        - Id: totalMemory
          Label: totalMemory
          MetricStat:
            Metric:
              Namespace: Application/MemesGenerator/DB
              MetricName: TotalDbMemory
            Stat: Average
            Period: !Ref Period
          ReturnData: false
        - Id: activeMemory
          Label: ActiveMemory
          MetricStat:
            Metric:
              Namespace: Application/MemesGenerator/DB
              MetricName: ActiveDbMemory
            Stat: Average
            Period: !Ref Period
          ReturnData: false
        - Expression: ((activeMemory)/(totalMemory)) * 100
          Id: percentofuse
          Label: PercentOfUseMemory
          ReturnData: true
      AlarmActions:
      - !Ref InfrastructureInformationTopic

  DatabaseMemoryUsageAlarmTier2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database Memory usage Tier 2
      AlarmName: !Sub ${Project}-${Stage}-${Component}-db-mem-usage-alarm-tier-2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Threshold: 80
      Metrics:
        - Id: totalMemory
          Label: totalMemory
          MetricStat:
            Metric:
              Namespace: Application/MemesGenerator/DB
              MetricName: TotalDbMemory
            Stat: Average
            Period: !Ref Period
          ReturnData: false
        - Id: activeMemory
          Label: ActiveMemory
          MetricStat:
            Metric:
              Namespace: Application/MemesGenerator/DB
              MetricName: ActiveDbMemory
            Stat: Average
            Period: !Ref Period
          ReturnData: false
        - Expression: ((activeMemory)/(totalMemory)) * 100
          Id: percentofuse
          Label: PercentOfUseMemory
          ReturnData: true
      AlarmActions:
      - !Ref InfrastructureInformationTopic

  DatabaseMemoryUsageAlarmTier3:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Database Memory usage Tier 3
      AlarmName: !Sub ${Project}-${Stage}-${Component}-db-mem-usage-alarm-tier-3
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Threshold: 90
      Metrics:
        - Id: totalMemory
          Label: totalMemory
          MetricStat:
            Metric:
              Namespace: Application/MemesGenerator/DB
              MetricName: TotalDbMemory
            Stat: Average
            Period: !Ref Period
          ReturnData: false
        - Id: activeMemory
          Label: ActiveMemory
          MetricStat:
            Metric:
              Namespace: Application/MemesGenerator/DB
              MetricName: ActiveDbMemory
            Stat: Average
            Period: !Ref Period
          ReturnData: false
        - Expression: ((activeMemory)/(totalMemory)) * 100
          Id: percentofuse
          Label: PercentOfUseMemory
          ReturnData: true
      AlarmActions:
      - !Ref InfrastructureAlertsTopics

  ApplicationMemoryUsageAlarmTier1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: App Memory usage Tier 1
      AlarmName: !Sub ${Project}-${Stage}-${Component}-app-mem-usage-alarm-tier-1
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      Period: !Ref Period
      MetricName: mem_used_percent
      Namespace: Application/MemesGenerator
      Threshold: 70
      Statistic: Average
      AlarmActions:
      - !Ref InfrastructureInformationTopic

  ApplicationMemoryUsageAlarmTier2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: App Memory usage Tier 2
      AlarmName: !Sub ${Project}-${Stage}-${Component}-app-mem-usage-alarm-tier-2
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      Period: !Ref Period
      MetricName: mem_used_percent
      Namespace: Application/MemesGenerator
      Threshold: 80
      Statistic: Average
      AlarmActions:
      - !Ref InfrastructureInformationTopic

  ApplicationMemoryUsageAlarmTier3:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: App Memory usage Tier 3
      AlarmName: !Sub ${Project}-${Stage}-${Component}-app-mem-usage-alarm-tier-3
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      Period: !Ref Period
      MetricName: mem_used_percent
      Namespace: Application/MemesGenerator
      Threshold: 90
      Statistic: Average
      AlarmActions:
      - !Ref InfrastructureAlertsTopics

  ApplicationCPUUsageAlarmTier1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Application Instance CPU usage Tier 1
      AlarmName: !Sub ${Project}-${Stage}-${Component}-app-cpu-usage-alarm-tier-1
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      Period: !Ref Period
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: ApplicationAutoScalingGroup
      Threshold: 60
      Statistic: Average
      AlarmActions:
      - !Ref InfrastructureInformationTopic

  ApplicationCPUUsageAlarmTier2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Application Instance CPU usage Tier 2
      AlarmName: !Sub ${Project}-${Stage}-${Component}-app-cpu-usage-alarm-tier-2
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      Period: !Ref Period
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: ApplicationAutoScalingGroup
      Threshold: 70
      Statistic: Average
      AlarmActions:
      - !Ref InfrastructureInformationTopic

  ApplicationCPUUsageAlarmTier3:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Application Instance CPU usage Tier 3
      AlarmName: !Sub ${Project}-${Stage}-${Component}-app-cpu-usage-alarm-tier-3
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      Period: !Ref Period
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: ApplicationAutoScalingGroup
      Threshold: 90
      Statistic: Average
      AlarmActions:
      - !Ref InfrastructureAlertsTopics

  ApplicationErrorsAlarmTier1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Application Errors Alarms Tier 1
      AlarmName: !Sub ${Project}-${Stage}-${Component}-app-errors-alarm-tier-1
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 120
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Dimensions:
      - Name: LoadBalancer
        Value: !Ref LoadBalancerFullName
      Threshold: 10
      Statistic: Sum
      AlarmActions:
      - !Ref ApplicationInformationTopic
      - !Ref InfrastructureInformationTopic

  ApplicationErrorsAlarmTier2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Application Errors Alarms Tier 2
      AlarmName: !Sub ${Project}-${Stage}-${Component}-app-errors-alarm-tier-2
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 120
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Dimensions:
      - Name: LoadBalancer
        Value: !Ref LoadBalancerFullName
      Threshold: 25
      Statistic: Sum
      AlarmActions:
      - !Ref ApplicationAlertsTopic
      - !Ref InfrastructureInformationTopic

  ApplicationErrorsAlarmTier3:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Application Errors Alarms Tier 3
      AlarmName: !Sub ${Project}-${Stage}-${Component}-app-errors-alarm-tier-3
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 120
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Dimensions:
      - Name: LoadBalancer
        Value: !Ref LoadBalancerFullName
      Threshold: 50
      Statistic: Sum
      AlarmActions:
      - !Ref ApplicationAlertsTopic
      - !Ref InfrastructureAlertsTopics
