AWSTemplateFormatVersion: '2010-09-09'
Description: Groups of users allowed to assume roles

Parameters:
  GroupPrefix:
    Description: A prefix of the name of a group that is allowed to assume roles
    Type: String
  AdminRoleName:
    Description: A name of the admin role at the target account
    Type: String
    Default: Admin
  FullAccessRoleName:
    Description: A name of the full access role at the target account
    Type: String
    Default: FullAccess
  ReadOnlyRoleName:
    Description: A name of the read-only role at the target account
    Type: String
    Default: ReadOnly
  WorkingRoleName:
    Description: A name of the working role at the target account
    Type: String
    Default: Working
  TargetAccountNumber:
    Description: Account number where the assumed roles are deployed
    Type: String

Resources:
  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub ${GroupPrefix}-admin-group
      ManagedPolicyArns:
        - !Ref AssumeAdminRolePolicy
        - !Ref AssumeReadOnlyRolePolicy
        - !Ref AssumeWorkingRolePolicy
      Path: /

  FullAccessGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub ${GroupPrefix}-full-access-group
      ManagedPolicyArns:
        - !Ref AssumeAdminRolePolicy
        - !Ref AssumeFullAccessRolePolicy
        - !Ref AssumeReadOnlyRolePolicy
        - !Ref AssumeWorkingRolePolicy
      Path: /

  ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub ${GroupPrefix}-read-only-group
      ManagedPolicyArns:
        - !Ref AssumeReadOnlyRolePolicy
      Path: /

  WorkingGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub ${GroupPrefix}-working-group
      ManagedPolicyArns:
        - !Ref AssumeReadOnlyRolePolicy
        - !Ref AssumeWorkingRolePolicy
      Path: /

  AssumeAdminRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub Policy that allows to assume admin role on the ${TargetAccountNumber} account
      ManagedPolicyName: AssumeAdminRolePolicy
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - !Sub arn:aws:iam::${TargetAccountNumber}:role/${AdminRoleName}

  AssumeFullAccessRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub Policy that allows to assume FullAccess role on the ${TargetAccountNumber} account
      ManagedPolicyName: AssumeFullAccessRolePolicy
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - !Sub arn:aws:iam::${TargetAccountNumber}:role/${FullAccessRoleName}

  AssumeReadOnlyRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub Policy that allows to assume read-only role on the ${TargetAccountNumber} account
      ManagedPolicyName: AssumeReadOnlyRolePolicy
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - !Sub arn:aws:iam::${TargetAccountNumber}:role/${ReadOnlyRoleName}

  AssumeWorkingRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub Policy that allows to assume working role on the ${TargetAccountNumber} account
      ManagedPolicyName: AssumeWorkingRolePolicy
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - !Sub arn:aws:iam::${TargetAccountNumber}:role/${WorkingRoleName}