AWSTemplateFormatVersion: 2010-09-09
Description: Notification topics

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$

Resources:
  InfrastructureInformationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Project}-${Stage}-${Component}-infra-info-topic
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-infra-info-topic

  InfrastructureInformationTopicArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: ARN of SNS topic for infrastructure notifications - info
      Value: !Ref InfrastructureInformationTopic
      Name: !Sub /${Project}/${Stage}/${Component}/infra-info-topic/arn
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-infra-info-topic-arn

  InfrastructureAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Project}-${Stage}-${Component}-infra-alerts-topic
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-infra-alerts-topic

  InfrastructureAlertsTopicArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: ARN of SNS topic for infrastructure notifications - info
      Value: !Ref InfrastructureAlertsTopic
      Name: !Sub /${Project}/${Stage}/${Component}/infra-alerts-topic/arn
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-infra-alerts-topic-arn

  ApplicationInformationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Project}-${Stage}-${Component}-app-info-topic
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-app-info-topic

  ApplicationInformationTopicArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: ARN of SNS topic for application notifications - info
      Value: !Ref ApplicationInformationTopic
      Name: !Sub /${Project}/${Stage}/${Component}/app-info-topic/arn
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-app-info-topic-arn

  ApplicationAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Project}-${Stage}-${Component}-app-alerts-topic
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-app-alerts-topic

  ApplicationAlertsTopicArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: ARN of SNS topic for application notifications - alerts
      Value: !Ref ApplicationAlertsTopic
      Name: !Sub /${Project}/${Stage}/${Component}/app-alerts-topic/arn
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-app-alerts-topic-arn

  SecurityInformationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Project}-${Stage}-${Component}-security-info-topic
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-security-info-topic

  SecurityInformationTopicArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: ARN of SNS topic for security notifications - info
      Value: !Ref SecurityInformationTopic
      Name: !Sub /${Project}/${Stage}/${Component}/security-info-topic/arn
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-security-alerts-topic-arn

  SecurityAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Project}-${Stage}-${Component}-security-alerts-topic
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-security-alerts-topic

  SecurityAlertsTopicArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: ARN of SNS topic for security notifications - alerts
      Value: !Ref SecurityAlertsTopic
      Name: !Sub /${Project}/${Stage}/${Component}/security-alerts-topic/arn
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-security-alerts-topic-arn

  SNSPolicyDocument:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: RootPolicyDocument
        Version: '2012-10-17'
        Statement:
          - Sid: SNSPolicyDocument
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource:
            - !Ref SecurityAlertsTopic
      Topics:
        - !Ref ApplicationInformationTopic
        - !Ref ApplicationAlertsTopic
        - !Ref InfrastructureInformationTopic
        - !Ref InfrastructureAlertsTopic
        - !Ref SecurityInformationTopic
        - !Ref SecurityAlertsTopic

Outputs:
  InfrastructureInformationTopicArn:
    Description: ARN of SNS topic for infrastructure notifications - info
    Value: !Ref InfrastructureInformationTopic
  InfrastructureInformationTopicArnParam:
    Description: Name of the SSM parameter that stores ARN of SNS topic for infrastructure notifications - info
    Value: !Ref InfrastructureInformationTopicArnParam
  InfrastructureAlertsTopicArn:
    Description: ARN of SNS topic for infrastructure notifications - alerts
    Value: !Ref InfrastructureAlertsTopic
  InfrastructureAlertsTopicArnParam:
    Description: Name of the SSM parameter that stores ARN of SNS topic for infrastructure notifications - alerts
    Value: !Ref InfrastructureAlertsTopicArnParam
  ApplicationInformationTopicArn:
    Description: ARN of SNS topic for application notifications - info
    Value: !Ref ApplicationInformationTopic
  ApplicationInformationTopicArnParam:
    Description: Name of the SSM parameter that stores ARN of SNS topic for application notifications - info
    Value: !Ref ApplicationInformationTopicArnParam
  ApplicationAlertsTopicArn:
    Description: ARN of SNS topic for application notifications - alerts
    Value: !Ref ApplicationAlertsTopic
  ApplicationAlertsTopicArnParam:
    Description: Name of the SSM parameter that stores ARN of SNS topic for application notifications - alerts
    Value: !Ref ApplicationAlertsTopicArnParam
  SecurityInformationTopicArn:
    Description: ARN of SNS topic for security notifications - info
    Value: !Ref SecurityInformationTopic
  SecurityInformationTopicArnParam:
    Description: Name of the SSM parameter that stores ARN of SNS topic for security notifications - info
    Value: !Ref SecurityInformationTopicArnParam
  SecurityAlertsTopicArn:
    Description: ARN of SNS topic for security notifications - alerts
    Value: !Ref SecurityAlertsTopic
  SecurityAlertsTopicArnParam:
    Description: Name of the SSM parameter that stores ARN of SNS topic for security notifications - alerts
    Value: !Ref SecurityAlertsTopicArnParam
