
AWSTemplateFormatVersion: '2010-09-09'
Description: ROOT-AWS-Console-Sign-In-via-CloudTrail

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$

Resources:
  RootLoginEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Events rule for monitoring root AWS Console Sign In activity
      EventPattern:
        detail-type:
        - AWS Console Sign In via CloudTrail
        detail:
          userIdentity:
            type:
            - Root
      Name: !Sub ${Project}-${Stage}-${Component}-root-activity-alert
      State: ENABLED
      Targets:
      - Arn: !Ref RootActivityAlertsTopic
        Id: SecurityAlertsTopic

  RootActivityAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Project}-${Stage}-${Component}-security-alerts-topic
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-security-alerts-topic

  SNSPolicyDocument:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: RootPolicyDocument
        Version: '2012-10-17'
        Statement:
          - Sid: SNSPolicyDocument
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource:
            - !Ref RootActivityAlertsTopic
      Topics:
        - !Ref RootActivityAlertsTopic
