AWSTemplateFormatVersion: 2010-09-09
Description: Template for JumpHost

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  ImageId:
    Description: Id of the latest amazon-linux-2 AMI
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  InstanceType:
    Description: Type of instance for Jump Host
    Type: String
    Default: t2.micro
  JumpHostSecurityGroup:
    Description: JumpHost Security Group from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  KeyPairName:
    Description: Key pair Name to auth Vm
    Type: String
    Default: ''
  PublicSubnetId:
    Description: Public Subnet Id from the SSM
    Type: AWS::SSM::Parameter::Value<String>

Conditions:
  UseKeyPair: !Not [!Equals [!Ref KeyPairName, '']]

Resources:
  JumpHostInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      KeyName: !If
        - UseKeyPair
        - !Ref KeyPairName
        - !Ref AWS::NoValue
      IamInstanceProfile: !Ref JumpHostInstanceProfile
      InstanceType: !Ref  InstanceType
      SecurityGroupIds:
        - !Ref JumpHostSecurityGroup
      SubnetId: !Ref PublicSubnetId
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo amazon-linux-extras enable postgresql11
          sudo yum clean metadata
          sudo yum install postgresql -y
          sudo yum install jq -y
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-jumphost-instance

  JumpHostInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref JumpHostInstanceRole

  JumpHostInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: JumpHostPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: GetSecretValue
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:ListSecretVersionIds
                  - secretsmanager:ListSecrets
                Resource:
                  - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Project}/${Stage}/*

Outputs:
  JumpHostInstanceId:
    Description: The ID of Jump Host Instance
    Value: !Ref JumpHostInstance
  JumpHostInstancePublicIp:
    Description: Public IP address of the jumphost instance
    Value: !GetAtt JumpHostInstance.PublicIp
