AWSTemplateFormatVersion: 2010-09-09
Description: Autoscaling template for JumpHost

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  LaunchTemplateId:
    Description: Launch template ID
    Type: AWS::SSM::Parameter::Value<String>
  LaunchTemplateLatestVersion:
    Description: Launch template latest version
    Type: AWS::SSM::Parameter::Value<String>
  PublicSubnetId:
    Description: Public Subnet Id from the SSM
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  JumpHostAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateId
        Version: !Ref LaunchTemplateLatestVersion
      MinSize: "1"
      MaxSize: "1"
      DesiredCapacity: "1"
      HealthCheckType: EC2
      VPCZoneIdentifier:
        - !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-jumphost-asg
          PropagateAtLaunch: false

  ScheduledActionOut:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName:
        Ref: "JumpHostAutoScalingGroup"
      MaxSize: 1
      MinSize: 1
      DesiredCapacity: 1
      Recurrence: "0 7 * * 1-5" # 9:00 in utc +2 (POLAND)

  ScheduledActionIn:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName:
        Ref: "JumpHostAutoScalingGroup"
      MaxSize: 0
      MinSize: 0
      DesiredCapacity: 0
      Recurrence: "0 15 * * 1-5" # 17:00 in utc +2 (POLAND)

Outputs:
  AutoScalingGroupName:
    Description: Name of the autoscaling group
    Value: !Ref JumpHostAutoScalingGroup
