AWSTemplateFormatVersion: 2010-09-09
Description: Template for log bucket

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$

Resources:
  S3LogBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl:  LogDeliveryWrite
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-log-bucket

  S3LogBucketNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component} Log Bucket Name
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/log-bucket/name
      Value: !Ref S3LogBucket
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-log-bucket-name-param

  S3LogBucketArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component} Log Bucket Arn
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/log-bucket/arn
      Value: !GetAtt S3LogBucket.Arn
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-log-bucket-arn

Outputs:
  S3BLogBucketName:
    Value: !Ref S3LogBucket
    Description: S3 Log Bucket Name
  S3LogBucketParamName:
    Description: The name of the SSM parameter where the Name of the Log Bucket is stored
    Value: !Ref S3LogBucketNameParam
  S3LogBucketArnParam:
    Description: The name of the SSM parameter where the Arn of the Log Bucket is stored
    Value: !Ref S3LogBucketArnParam
