AWSTemplateFormatVersion: 2010-09-09
Description: Set of SSM parameters that store AWS accounts ids

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  SharedStage:
    Description: Stage name for shared resources
    Type: String
    AllowedValues:
      - shared-dev
      - shared-test
      - shared
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  DevAccountId:
    Description: ID of the development AWS Account
    Type: String
  # ProdAccountId:
  #   Description: ID of the production AWS Account
  #   Type: String
  SharedResourcesAccountId:
    Description: ID of the shared resources AWS Account
    Type: String
  # TestAccountId:
  #   Description: ID of the production AWS Account
  #   Type: String

Resources:
  DevAccountIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type:  String
      Name: !Sub /${Project}/${SharedStage}/${Component}/account-dev/id
      Value: !Ref DevAccountId
      Description: Stores AWS Account Id for a development account
      Tags:
        Name: !Sub ${Project}-${SharedStage}-${Component}-account-dev-id

  # ProdAccountIdParam:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Type:  String
  #     Name: !Sub /${Project}/${SharedStage}/${Component}/account-prod/id
  #     Value: !Ref ProdAccountId
  #     Description: Stores AWS Account Id for a prod account
  #     Tags:
  #       Name: !Sub ${Project}-${SharedStage}-${Component}-account-prod-id

  SharedResourcesAccountIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type:  String
      Name: !Sub /${Project}/${SharedStage}/${Component}/account-shared/id
      Value: !Ref SharedResourcesAccountId
      Description: Stores AWS Account Id for a shared resources account
      Tags:
        Name: !Sub ${Project}-${SharedStage}-${Component}-account-shared-id

  # TestAccountIdParam:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Type:  String
  #     Name: !Sub /${Project}/${SharedStage}/${Component}/account-test/id
  #     Value: !Ref TestAccountId
  #     Description: Stores AWS Account Id for a test account
  #     Tags:
  #       Name: !Sub ${Project}-${SharedStage}-${Component}-account-test-id

Outputs:
  DevAccountId:
    Description: Value of the SSM that stores id of AWS development account
    Value: !GetAtt DevAccountIdParam.Value
  DevAccountIdParamName:
    Description: Name of the SSM that stores id of AWS development account
    Value: !Ref DevAccountIdParam
  # ProdAccountId:
  #   Description: Value of the SSM that stores id of AWS prod account
  #   Value: !GetAtt ProdAccountIdParam.Value
  # ProdAccountIdParamName:
  #   Description: Name of the SSM that stores id of AWS prod account
  #   Value: !Ref ProdAccountIdParam
  SharedResourcesAccountId:
    Description: Value of the SSM that stores id of AWS shared resources account
    Value: !GetAtt SharedResourcesAccountIdParam.Value
  SharedResourcesAccountIdParamName:
    Description: Name of the SSM that stores id of AWS shared resources account
    Value: !Ref SharedResourcesAccountIdParam
  # TestAccountId:
  #   Description: Value of the SSM that stores id of AWS test account
  #   Value: !GetAtt TestAccountIdParam.Value
  # TestAccountIdParamName:
  #   Description: Name of the SSM that stores id of AWS test account
  #   Value: !Ref TestAccountIdParam