AWSTemplateFormatVersion: 2010-09-09
Description: Test Deployment pipeline

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  SharedStage:
    Description: Stage name for shared resources
    Type: String
    AllowedValues:
      - shared-dev
      - shared-test
      - shared
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  ArtifactBucket:
    Description: A bucket for CodePipeline artifacts
    Type: AWS::SSM::Parameter::Value<String>
  BuildImageName:
    Description: Docker image for application build
    Type: String
    Default: aws/codebuild/amazonlinux2-x86_64-standard:3.0
  BuildSpecFile:
    Description: Name of the buildspec file
    Type: String
    Default: buildspec.yaml
  CodeBuildRoleName:
    Description: Name of the IAM role used by CodeBuild
    Type: AWS::SSM::Parameter::Value<String>
  S3Key:
    Description: Folder in S3 bucket for packaged templates & artifacts
    Type: String
    Default: codebuild-artifacts
  ProjectFunction:
    Description: Function for the project
    Type: String
  TargetStage:
    Description: Target stage name - for which stage the artifacts are created for
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
      - shared
      - shared-dev
      - shared-test

Resources:
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${Project}-${SharedStage}-${Component}-${ProjectFunction}
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub ${Project}/${Component}/buildspec/${BuildSpecFile}
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref BuildImageName
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !Ref ArtifactBucket
          - Name: PROJECT
            Value: !Ref Project
          - Name: TARGET_STAGE
            Value: !Ref TargetStage
          - Name: S3_KEY
            Value: !Ref S3Key
          - Name: REGION
            Value: !Ref AWS::Region
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/${CodeBuildRoleName}
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${SharedStage}-${Component}-${ProjectFunction}

Outputs:
  BuildProjectName:
    Value: !Ref BuildProject
