AWSTemplateFormatVersion: 2010-09-09
Description: Shared resources for CICD

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  SharedStage:
    Description: Stage name for shared resources
    Type: String
    AllowedValues:
      - shared-dev
      - shared-test
      - shared
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  DevAccountId:
    Description: ID of the development AWS Account
    Type: AWS::SSM::Parameter::Value<String>
  DevAccountDeploymentRoleName:
    Description: A role name for CI/CD in the dev account
    Type: AWS::SSM::Parameter::Value<String>
  DevAccountServiceRoleName:
    Description: A role name for CI/CD in the dev account
    Type: AWS::SSM::Parameter::Value<String>
  KmsKeyArn:
    Description: ARN of KMS key used for encryption of CICD resources
    Type: AWS::SSM::Parameter::Value<String>
  RepositoryName:
    Description: Name of the repository with infrastructure code
    Type: AWS::SSM::Parameter::Value<String>
  # ProdAccountId:
  #   Description: ID of the production AWS Account
  #   Type: AWS::SSM::Parameter::Value<String>
  # ProdAccountDeploymentRoleName:
  #   Description: A role name for CI/CD in the production account
  #   Type: AWS::SSM::Parameter::Value<String>
  # ProdAccountServiceRoleName:
  #   Description: A role name for CI/CD in the production account
  #   Type: AWS::SSM::Parameter::Value<String>
  # TestAccountId:
  #   Description: ID of the test AWS Account
  #   Type: AWS::SSM::Parameter::Value<String>
  # TestAccountDeploymentRoleName:
  #   Description: A role name for CI/CD in the dev account
  #   Type: AWS::SSM::Parameter::Value<String>
  # TestAccountServiceRoleName:
  #   Description: A role name for CI/CD in the test account
  #   Type: AWS::SSM::Parameter::Value<String>

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KmsKeyArn
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${SharedStage}-${Component}-artifacts-bucket-name

  ArtifactBucketNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${SharedStage}-${Component} Artifact Bucket Name
      Tier: Standard
      Name: !Sub /${Project}/${SharedStage}/${Component}/artifact-bucket/name
      Value: !Ref ArtifactBucket
      Tags:
        Name: !Sub ${Project}-${SharedStage}-${Component}-artifact-bucket-name

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: CrossAccountAccess
            Effect: Allow
            Action:
              - s3:GetBucketPolicy
              - s3:ListBucket
            Principal:
              AWS:
                - !Sub arn:aws:iam::${DevAccountId}:role/${DevAccountServiceRoleName}
                - !Sub arn:aws:iam::${DevAccountId}:role/${DevAccountDeploymentRoleName}
                # - !Sub arn:aws:iam::${ProdAccountId}:role/${ProdAccountDeploymentRoleName}
                # - !Sub arn:aws:iam::${ProdAccountId}:role/${ProdAccountServiceRoleName}
                # - !Sub arn:aws:iam::${TestAccountId}:role/${TestAccountServiceRoleName}
                # - !Sub arn:aws:iam::${TestAccountId}:role/${TestAccountDeploymentRoleName}
            Resource:
              - !GetAtt ArtifactBucket.Arn
          - Sid: CrossAccountAccessToObjects
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
            Principal:
              AWS:
                - !Sub arn:aws:iam::${DevAccountId}:role/${DevAccountServiceRoleName}
                - !Sub arn:aws:iam::${DevAccountId}:role/${DevAccountDeploymentRoleName}
                # - !Sub arn:aws:iam::${ProdAccountId}:role/${ProdAccountDeploymentRoleName}
                # - !Sub arn:aws:iam::${ProdAccountId}:role/${ProdAccountServiceRoleName}
                # - !Sub arn:aws:iam::${TestAccountId}:role/${TestAccountServiceRoleName}
                # - !Sub arn:aws:iam::${TestAccountId}:role/${TestAccountDeploymentRoleName}
            Resource:
              - !Sub ${ArtifactBucket.Arn}/*

  SourceBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KmsKeyArn
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${SharedStage}-${Component}-source-bucket-name

  SourceBucketNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${SharedStage}-${Component} Source Bucket Name
      Tier: Standard
      Name: !Sub /${Project}/${SharedStage}/${Component}/source-bucket/name
      Value: !Ref SourceBucket
      Tags:
        Name: !Sub ${Project}-${SharedStage}-${Component}-source-bucket-name

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: code-build
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - sns:Publish
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub ${ArtifactBucket.Arn}/*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub ${ArtifactBucket.Arn}/*
                  - !Sub ${SourceBucket.Arn}/*
              - Effect: Allow
                Action:
                  - s3:GetBucketVersioning
                  - s3:ListBucket
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !GetAtt SourceBucket.Arn
              - Effect: Allow
                Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                  - kms:DescribeKey
                Resource: !Ref KmsKeyArn
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${Project}-application-pic*/*.jpg
                  - !Sub arn:aws:s3:::${Project}-application-pic*/*.png
                  - !Sub arn:aws:s3:::${Project}-application-conf*/service/*
                  - !Sub arn:aws:s3:::${Project}-application-conf*/cloudwatch/*
              - Effect: Allow
                Action:
                  - ssm:SendCommand
                Resource:
                  - !Sub arn:aws:ssm:*:*:document/${Project}-operations-create-db-user
              - Effect: Allow
                Action:
                  - ssm:SendCommand
                Resource:
                  - arn:aws:ec2:*:*:instance/*
                Condition:
                  StringEquals:
                    'aws:ResourceTag/Function': jumphost
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:*:*:parameter/${Project}/*/application/*
                  - !Sub arn:aws:ssm:*:*:parameter/${Project}/*/application/*
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${SharedStage}-${Component}-codebuild-role

  CodeBuildRoleNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${SharedStage}-${Component} CodeBuild Role Name
      Tier: Standard
      Name: !Sub /${Project}/${SharedStage}/${Component}/codebuild-role/name
      Value: !Ref CodeBuildRole
      Tags:
        Name: !Sub ${Project}-${SharedStage}-${Component}-codebuild-role-name

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: code-pipeline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub ${ArtifactBucket.Arn}/*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub ${ArtifactBucket.Arn}/*
                  - !Sub ${SourceBucket.Arn}/*
              - Effect: Allow
                Action:
                  - s3:GetBucketPolicy
                  - s3:GetBucketVersioning
                  - s3:ListBucket
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !GetAtt SourceBucket.Arn
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                Resource:
                  - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*
                  - !Sub arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31
              - Effect: Allow
                Action:
                - kms:Encrypt
                - kms:Decrypt
                - kms:ReEncrypt*
                - kms:GenerateDataKey*
                - kms:DescribeKey
                Resource: !Ref KmsKeyArn
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - !Sub arn:aws:iam::${DevAccountId}:role/${DevAccountServiceRoleName}
                  # - !Sub arn:aws:iam::${ProdAccountId}:role/${ProdAccountServiceRoleName}
                  # - !Sub arn:aws:iam::${TestAccountId}:role/${TestAccountServiceRoleName}
              - Effect: Allow
                Action:
                  - codecommit:BatchGet*
                  - codecommit:BatchDescribe*
                  - codecommit:Describe*
                  - codecommit:Get*
                  - codecommit:List*
                  - codecommit:GitPull
                  - codecommit:UploadArchive
                Resource:
                  - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${RepositoryName}
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${SharedStage}-${Component}-codepipeline-role

  CodePipelineRoleNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${SharedStage}-${Component} CodePipeline Role Name
      Tier: Standard
      Name: !Sub /${Project}/${SharedStage}/${Component}/codepipeline-role/name
      Value: !Ref CodePipelineRole
      Tags:
        Name: !Sub ${Project}-${SharedStage}-${Component}-codepipeline-role-name

Outputs:
  ArtifactBucketName:
    Description: Name of a bucket for artifacts
    Value: !Ref ArtifactBucket
  ArtifactBucketNameParamName:
    Description: The name of the SSM parameter storing the name of the bucket with artifacts
    Value: !Ref ArtifactBucketNameParam
  SourceBucketName:
    Description: Name of a bucket for source
    Value: !Ref SourceBucket
  SourceBucketNameParamName:
    Description: The name of the SSM parameter storing the name of the bucket with source code
    Value: !Ref SourceBucketNameParam
  CodeBuildRoleName:
    Description: Name of IAM role used by CodeBuild
    Value: !Ref CodeBuildRole
  CodeBuildRoleNameParamName:
    Description: The name of the SSM parameter storing the name of the role assumed by CodeBuild
    Value: !Ref CodeBuildRoleNameParam
  CodePipelineRoleName:
    Description: Name of IAM role used by CodePipeline
    Value: !Ref CodePipelineRole
  CodePipelinedRoleNameParamName:
    Description: The name of the SSM parameter storing the name of the role assumed by CodePipeline
    Value: !Ref CodePipelineRoleNameParam
