AWSTemplateFormatVersion: 2010-09-09
Description: Template for creating deployment roles in dev, test & prod accounts

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Stage:
    Description: Stage name
    Type: String
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  KmsKeyArn:
    Description: ARN of KMS key used for encryption of CICD resources
    Type: String
  # SecondaryKmsKeyArn:
  #   Description: ARN of KMS key used for encryption of CICD resources in secondary region
  #   Type: String
  SharedResourcesAccountId:
    Description: ID of shared services account
    Type: String

Resources:
  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Policies:
        - PolicyName: key-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - kms:Encrypt
                - kms:Decrypt
                - kms:ReEncrypt*
                - kms:GenerateDataKey*
                - kms:DescribeKey
                Resource:
                  - !Ref KmsKeyArn
                  # - !Ref SecondaryKmsKeyArn
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-deployment-role

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref SharedResourcesAccountId
              Service:
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: key-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - kms:Encrypt
                - kms:Decrypt
                - kms:ReEncrypt*
                - kms:GenerateDataKey*
                - kms:DescribeKey
                Resource:
                  - !Ref KmsKeyArn
                  # - !Ref SecondaryKmsKeyArn
        - PolicyName: cloudformation-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - cloudformation:*
                Resource: "*"
        - PolicyName: s3-object-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource: "*"
        - PolicyName: iam-pass
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - iam:PassRole
                Resource:
                  - !GetAtt DeploymentRole.Arn
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-service-role

Outputs:
  DeploymentRoleName:
    Value: !Ref DeploymentRole
  ServiceRoleName:
    Value: !Ref ServiceRole
