AWSTemplateFormatVersion: 2010-09-09
Description: AWS EventBridge rules for pipelines

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  SharedStage:
    Description: Stage name for shared resources
    Type: String
    AllowedValues:
      - shared-dev
      - shared-test
      - shared
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  BranchName:
    Description: Branch in infrastructure code repo
    Type: String
  CreateResourcesPipelineArn:
    Description: Create resources pipeline ARN
    Type: AWS::SSM::Parameter::Value<String>
  DeleteResourcesPipelineArn:
    Description: Delete resources pipeline ARN
    Type: AWS::SSM::Parameter::Value<String>
  RepositoryName:
    Description: Name of the repository with infrastructure code
    Type: AWS::SSM::Parameter::Value<String>
  ScheduleCreation:
    Description: Determines if creation of resources should be performed on schedule
    Type: String
    AllowedValues:
      - 'yes'
      - 'no'
    Default: 'no'
  ScheduleDeletion:
    Description: Determines if deletion of resources should be performed on schedule
    Type: String
    AllowedValues:
      - 'yes'
      - 'no'
    Default: 'no'

Conditions:
  IsCreationScheduled: !Equals [ !Ref ScheduleCreation, 'yes']
  IsDeletionScheduled: !Equals [ !Ref ScheduleDeletion, 'yes']

Resources:
  EventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: cwe-pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource:
                  - !Ref CreateResourcesPipelineArn
                  - !Ref DeleteResourcesPipelineArn
              - Effect: Allow
                Action: sns:Publish
                Resource:
                  - !Ref CicdNotificationTopic

  CodeUpdateEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${RepositoryName}-code-update-${BranchName}
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - 'CodeCommit Repository State Change'
        resources:
          - !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${RepositoryName}
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - !Ref BranchName
      Targets:
        - Arn: !Ref CreateResourcesPipelineArn
          RoleArn: !GetAtt EventRole.Arn
          Id: !Sub ${Project}-${SharedStage}-${Component}-create-resources-pipeline
        - Arn: !Ref CicdNotificationTopic
          Id: !Sub ${Project}-${SharedStage}-${Component}-send-notification

  CreateResourcesEventRule:
    Type: AWS::Events::Rule
    Condition: IsCreationScheduled
    Properties:
      Name: !Sub ${Project}-${SharedStage}-${Component}-create-resources-scheduled
      ScheduleExpression: cron(0 7 ? * 1-5 *)
      Targets:
        - Arn: !Ref CreateResourcesPipelineArn
          RoleArn: !GetAtt EventRole.Arn
          Id: !Sub ${Project}-${SharedStage}-${Component}-create-resources-scheduled

  DeleteResourcesEventRule:
    Type: AWS::Events::Rule
    Condition: IsDeletionScheduled
    Properties:
      Name: !Sub ${Project}-${SharedStage}-${Component}-delete-resources-scheduled
      ScheduleExpression: cron(0 18 ? * 1-5 *)
      Targets:
        - Arn: !Ref DeleteResourcesPipelineArn
          RoleArn: !GetAtt EventRole.Arn
          Id: !Sub ${Project}-${SharedStage}-${Component}-delete-resources-scheduled

  CicdNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Project}-${SharedStage}-${Component}-topic

