AWSTemplateFormatVersion: 2010-09-09
Description: Set of SSM parameters that store deployment role names

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  SharedStage:
    Description: Stage name for shared resources
    Type: String
    AllowedValues:
      - shared-dev
      - shared-test
      - shared
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  DevAccountDeploymentRoleName:
    Description: A role name for CI/CD in the development account
    Type: String
  DevAccountServiceRoleName:
    Description: A role name for CI/CD in the development account
    Type: String
  # ProdAccountDeploymentRoleName:
  #   Description: A role name for CI/CD in the production account
  #   Type: String
  # ProdAccountServiceRoleName:
  #   Description: A role name for CI/CD in the production account
  #   Type: String
  # TestAccountDeploymentRoleName:
  #   Description: A role name for CI/CD in the test account
  #   Type: String
  # TestAccountServiceRoleName:
  #   Description: A role name for CI/CD in the test account
  #   Type: String

Resources:
  DevAccountDeploymentRoleNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type:  String
      Name: !Sub /${Project}/${SharedStage}/${Component}/deployment-role-dev/name
      Value: !Ref DevAccountDeploymentRoleName
      Description: Stores the name of the deployment role in the development account
      Tags:
        Name: !Sub ${Project}-${SharedStage}-${Component}-deployment-role-dev-name

  DevAccountServiceRoleNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type:  String
      Name: !Sub /${Project}/${SharedStage}/${Component}/service-role-dev/name
      Value: !Ref DevAccountServiceRoleName
      Description: Stores the name of the service role in the development account
      Tags:
        Name: !Sub ${Project}-${SharedStage}-${Component}-service-role-dev-name

  # ProdAccountDeploymentRoleNameParam:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Type:  String
  #     Name: !Sub /${Project}/${SharedStage}/${Component}/deployment-role-prod/name
  #     Value: !Ref ProdAccountDeploymentRoleName
  #     Description: Stores the name of the deployment role in the prod account
  #     Tags:
  #       Name: !Sub ${Project}-${SharedStage}-${Component}-deployment-role-prod-name

  # ProdAccountServiceRoleNameParam:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Type:  String
  #     Name: !Sub /${Project}/${SharedStage}/${Component}/service-role-prod/name
  #     Value: !Ref ProdAccountServiceRoleName
  #     Description: Stores the name of the Service role in the prod account
  #     Tags:
  #       Name: !Sub ${Project}-${SharedStage}-${Component}-service-role-prod-name

  # TestAccountDeploymentRoleNameParam:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Type:  String
  #     Name: !Sub /${Project}/${SharedStage}/${Component}/deployment-role-test/name
  #     Value: !Ref TestAccountDeploymentRoleName
  #     Description: Stores the name of the deployment role in the test account
  #     Tags:
  #       Name: !Sub ${Project}-${SharedStage}-${Component}-deployment-role-test-name

  # TestAccountServiceRoleNameParam:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Type:  String
  #     Name: !Sub /${Project}/${SharedStage}/${Component}/service-role-test/name
  #     Value: !Ref TestAccountServiceRoleName
  #     Description: Stores the name of the service role in the test account
  #     Tags:
  #       Name: !Sub ${Project}-${SharedStage}-${Component}-service-role-test-name

Outputs:
  DevAccountDeploymentRoleName:
    Description: Value of the SSM parameter that stores the name of the deployment role in the development account
    Value: !GetAtt DevAccountDeploymentRoleNameParam.Value
  DevAccountDeploymentRoleNameParamName:
    Description: Name of the SSM parameter that stores the name of the deployment role in the development account
    Value: !Ref DevAccountDeploymentRoleNameParam
  DevAccountServiceRoleName:
    Description: Value of the SSM parameter that stores the name of the service role in the development account
    Value: !GetAtt DevAccountServiceRoleNameParam.Value
  DevAccountServiceRoleNameParamName:
    Description: Name of the SSM parameter that stores the name of the service role in the development account
    Value: !Ref DevAccountServiceRoleNameParam
  # ProdAccountDeploymentRoleName:
  #   Description: Value of the SSM parameter that stores the name of the deployment role in the production account
  #   Value: !GetAtt ProdAccountDeploymentRoleNameParam.Value
  # ProdAccountDeploymentRoleNameParamName:
  #   Description: Name the SSM parameter that stores the name of the deployment role in the production account
  #   Value: !Ref ProdAccountDeploymentRoleNameParam
  # ProdAccountServiceRoleName:
  #   Description: Value of the SSM parameter that stores the name of the service role in the production account
  #   Value: !GetAtt ProdAccountServiceRoleNameParam.Value
  # ProdAccountServiceRoleNameParamName:
  #   Description: Name the SSM parameter that stores the name of the service role in the production account
  #   Value: !Ref ProdAccountServiceRoleNameParam
  # TestAccountDeploymentRoleName:
  #   Description: Value of the SSM parameter that stores the name of the deployment role in the test account
  #   Value: !GetAtt TestAccountDeploymentRoleNameParam.Value
  # TestAccountRoleDeploymentNameParamName:
  #   Description: Name of the SSM parameter that stores the name of the deployment role in the test account
  #   Value: !Ref TestAccountDeploymentRoleNameParam
  # TestAccountServiceRoleName:
  #   Description: Value of the SSM parameter that stores the name of the service role in the test account
  #   Value: !GetAtt TestAccountServiceRoleNameParam.Value
  # TestAccountRoleServiceNameParamName:
  #   Description: Name of the SSM parameter that stores the name of the service role in the test account
  #   Value: !Ref TestAccountServiceRoleNameParam
