AWSTemplateFormatVersion: 2010-09-09
Description: Deployment pipeline for deletion of selected resources

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  SharedStage:
    Description: Stage name for shared resources
    Type: String
    AllowedValues:
      - shared-dev
      - shared-test
      - shared
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  ArtifactBucket:
    Description: A bucket for CodePipeline artifacts
    Type: AWS::SSM::Parameter::Value<String>
  BranchName:
    Description: Branch in infrastructure code repo
    Type: String
  CodePipelineRoleName:
    Description: Name of the IAM role used by CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
  CrossRegionDeployment:
    Description: Is the deployment in the same or another region than the pipeline?
    Type: String
    AllowedValues:
      - 'yes'
      - 'no'
    Default: 'no'
  DeploymentRegion:
    Description: Region for deployments
    Type: String
    AllowedValues:
      - eu-central-1
      - eu-west-1
    Default: eu-central-1
  DeploymentRoleName:
    Description: A role name for CI/CD in the target account
    Type: AWS::SSM::Parameter::Value<String>
  KmsKeyArn:
    Description: ARN of KMS key that is used for artifacts' encryption
    Type: AWS::SSM::Parameter::Value<String>
  RepositoryName:
    Description: Name of the repository with infrastructure code
    Type: AWS::SSM::Parameter::Value<String>
  ServiceRoleName:
    Description: A role name for CI/CD in the target account
    Type: AWS::SSM::Parameter::Value<String>
  TargetAccountId:
    Description: ID of the Target AWS Account
    Type: AWS::SSM::Parameter::Value<String>
  TargetStage:
    Description: A target stage for deployment
    Type: String

Conditions:
  IsCrossRegionDeployment: !Equals [ !Ref CrossRegionDeployment, 'yes']
  IsDevOrTest: !Or
    - !Equals [ !Ref TargetStage, 'dev' ]
    - !Equals [ !Ref TargetStage, 'test' ]

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref AWS::StackName
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${CodePipelineRoleName}
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
        EncryptionKey:
          Id: !Ref KmsKeyArn
          Type: KMS
      Stages:
        - Name: Source
          Actions:
            - Name: TemplateSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              Configuration:
                BranchName: !Ref BranchName
                PollForSourceChanges: false
                RepositoryName: !Ref RepositoryName
              OutputArtifacts:
                - Name: !Sub SourceArtifacts-${Project}-${TargetStage}
        - Name: DeleteApplication
          Actions:
            - Name: ApplicationAutoScaling-Delete
              RunOrder: 10
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: DELETE_ONLY
                RoleArn: !Sub arn:aws:iam::${TargetAccountId}:role/${DeploymentRoleName}
                StackName: !Sub ${Project}-application-application-auto-scaling-${TargetStage}
              RoleArn: !Sub arn:aws:iam::${TargetAccountId}:role/${ServiceRoleName}
              Region: !If
                - IsCrossRegionDeployment
                - !Ref DeploymentRegion
                - !Ref AWS::Region
        - Name: DeleteNetworkResources
          Actions:
            - Name: NatGatewayA-Delete
              RunOrder: 31
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: DELETE_ONLY
                RoleArn: !Sub arn:aws:iam::${TargetAccountId}:role/${DeploymentRoleName}
                StackName: !Sub ${Project}-network-nat-gateway-a-${TargetStage}
              RoleArn: !Sub arn:aws:iam::${TargetAccountId}:role/${ServiceRoleName}
              Region: !If
                - IsCrossRegionDeployment
                - !Ref DeploymentRegion
                - !Ref AWS::Region
            - Name: NatGatewayB-Delete
              RunOrder: 31
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: DELETE_ONLY
                RoleArn: !Sub arn:aws:iam::${TargetAccountId}:role/${DeploymentRoleName}
                StackName: !Sub ${Project}-network-nat-gateway-b-${TargetStage}
              RoleArn: !Sub arn:aws:iam::${TargetAccountId}:role/${ServiceRoleName}
              Region: !If
                - IsCrossRegionDeployment
                - !Ref DeploymentRegion
                - !Ref AWS::Region
            - Name: LoadBalancer-Delete
              RunOrder: 40
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: DELETE_ONLY
                RoleArn: !Sub arn:aws:iam::${TargetAccountId}:role/${DeploymentRoleName}
                StackName: !Sub ${Project}-network-load-balancing-${TargetStage}
              RoleArn: !Sub arn:aws:iam::${TargetAccountId}:role/${ServiceRoleName}
              Region: !If
                - IsCrossRegionDeployment
                - !Ref DeploymentRegion
                - !Ref AWS::Region
      RestartExecutionOnUpdate: !If
        - IsDevOrTest
        - true
        - false
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${SharedStage}-${Component}-delete-pipeline

  PipelineArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project} ${SharedStage} ${Component} create resources pipeline for target stage ${TargetStage}
      Tier: Standard
      Name: !Sub /${Project}/${SharedStage}/${Component}/delete-resources-pipeline/${TargetStage}/arn
      Value: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${Pipeline}
      Tags:
        Name: !Sub ${Project}-${SharedStage}-${Component}-delete-resources-pipeline-${TargetStage}-arn


Outputs:
  PipelineName:
    Value: !Ref Pipeline
  PipelineArnParamName:
    Description: Name of the SSM parameter that stores the pipeline's ARN
    Value: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${Pipeline}
