AWSTemplateFormatVersion: 2010-09-09
Description: Template for ssm command which adds user to DB

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  SharedStage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$

Resources:
  SSMDocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: '2.2'
        description: Add user to db - run on jumphost-db
        parameters:
          Project:
            type: String
            description: Name of the project
          TargetStage:
            type: String
            description: Name of target stage where document will be run
          Region:
            type: String
            description: AWS region name
        mainSteps:
        - action: aws:runShellScript
          name: runCommands
          inputs:
            timeoutSeconds: 120
            runCommand:
              - |
                #!/bin/bash
                # Commands for jumphost-db (jumphost with additional db tools & permissions)

                PROJECT={{Project}}
                STAGE={{TargetStage}}
                REGION={{Region}}

                MASTERUSER_SECRET_NAME="$PROJECT/$STAGE/data/rds/masteruser-secret"
                APP_SECRET_NAME="$PROJECT/$STAGE/data/rds/app-user-secret"

                APP_SECRET=$(aws secretsmanager get-secret-value --secret-id $APP_SECRET_NAME --output text --query SecretString --region $REGION)
                DB_HOST=$(echo $APP_SECRET | jq '.host' | sed 's|\"||g')
                DB_NAME=$(echo $APP_SECRET | jq '.dbname' | sed 's|\"||g')
                DB_APP_USER=$(echo $APP_SECRET | jq '.username' | sed 's|\"||g')
                DB_APP_PASSWORD=$(echo $APP_SECRET | jq '.password' | sed 's|\"||g')

                MASTERUSER_SECRET=$(aws secretsmanager get-secret-value --secret-id $MASTERUSER_SECRET_NAME --output text --query SecretString --region $REGION)
                MASTERUSER_PASSWORD=$(echo $MASTERUSER_SECRET | jq '.password' | sed 's|\"||g')

                ##### create appuser #####

                PGPASSWORD=$MASTERUSER_PASSWORD psql -U masteruser -h $DB_HOST -d $DB_NAME -c "CREATE USER $DB_APP_USER WITH ENCRYPTED PASSWORD '$DB_APP_PASSWORD';"
                PGPASSWORD=$MASTERUSER_PASSWORD psql -U masteruser -h $DB_HOST -d $DB_NAME -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_APP_USER;"
      DocumentType: Command
      Name: !Sub ${Project}-${Component}-create-db-user

Outputs:
  DocumentName:
    Description: SSM document name for creating DB user
    Value: !Ref SSMDocument

