AWSTemplateFormatVersion: 2010-09-09
Description: Deployment pipeline for one target stage

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  SharedStage:
    Description: Stage name for shared resources
    Type: String
    AllowedValues:
      - shared-dev
      - shared-test
      - shared
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  ArtifactBucket:
    Description: A bucket for CodePipeline artifacts
    Type: AWS::SSM::Parameter::Value<String>
  BranchName:
    Description: Branch in infrastructure code repo
    Type: String
  CodePipelineRoleName:
    Description: Name of the IAM role used by CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
  RepositoryName:
    Description: Name of the repository with infrastructure code
    Type: AWS::SSM::Parameter::Value<String>
Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref AWS::StackName
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${CodePipelineRoleName}
      Stages:
        - Name: Source
          Actions:
            - Name: WebsiteSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              Configuration:
                BranchName: !Ref BranchName
                PollForSourceChanges: false
                RepositoryName: !Ref RepositoryName
              OutputArtifacts:
                - Name: !Sub SourceArtifacts-${Project}-${TargetStage}
        - Name: BuildArtifacts
          Actions:
            - Name: TestAndBuildArtifacts
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref TestAndBuildProject
              InputArtifacts:
                - Name: !Sub SourceArtifacts-${Project}-${TargetStage}
              OutputArtifacts:
                - Name: !Sub Artifacts-${Project}-${TargetStage}
