version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - ls -l
artifacts:
  files:
    - "**/*"
  name: mybuild
  base-directory: build
