AWSTemplateFormatVersion: 2010-09-09
Description: Template for static s3 website

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  LogBucketName:
    Description: Name of the Log Bucket
    Type: String

Resources:
  S3Website:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucketName
        LogFilePrefix: s3-website
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Component}-${Stage}-static-s3-website

  S3WebsitePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: S3WebsitePolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Website
                - /*
      Bucket: !Ref S3Website

Outputs:
  WebsiteURL:
    Value: !GetAtt S3Website.WebsiteURL
    Description: URL for website hosted on S3
  S3BucketName:
    Value: !Ref S3Website
    Description: S3 Bucket Name