AWSTemplateFormatVersion: 2010-09-09
Description: Template for a static s3 website

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project information
        Parameters:
          - Project
          - Component
      - Label:
          default: Deployment information
        Parameters:
          - Stage
    ParameterLabels:
      Project:
        default: What is the name of the project?
      Component:
        default: What is the component of the project that resources belong to?
      Stage:
        default: What stage do we deploy to?

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
    Default: dev
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$

Resources:
  S3Website:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-static-s3-website

  S3WebsitePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: S3WebsitePolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Website
                - /*
      Bucket: !Ref S3Website

Outputs:
  WebsiteURL:
    Value: !GetAtt S3Website.WebsiteURL
    Description: URL for website hosted on S3
  S3BucketName:
    Value: !Ref S3Website
    Description: S3 Bucket Name
