AWSTemplateFormatVersion: 2010-09-09
Description: Template for Application

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  LaunchTemplateId:
    Description: Launch template ID
    Type: AWS::SSM::Parameter::Value<String>
  LaunchTemplateVersion:
    Description: Launch template version
    Type: String
    Default: ''
  LaunchTemplateLatestVersion:
    Description: Launch template latest version
    Type: AWS::SSM::Parameter::Value<String>
  PrivateSubnetId:
    Description: Reference of the PrivateSubnetId from the SSM
    Type: AWS::SSM::Parameter::Value<String>

Conditions:
  UseProvidedTemplateVersion: !Not [ !Equals [!Ref LaunchTemplateVersion, ''] ]

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateId
        Version: !If
          - UseProvidedTemplateVersion
          - !Ref LaunchTemplateVersion
          - !Ref LaunchTemplateLatestVersion
      SubnetId: !Ref PrivateSubnetId

Outputs:
  InstanceId:
    Description: The ID of the Instance
    Value: !Ref Instance
