AWSTemplateFormatVersion: 2010-09-09
Description: Template for the application instance role

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  DbAppCredentialsSecretArn:
    Description: ARN of the secret that stores database credentials for the application
    Type: AWS::SSM::Parameter::Value<String>
  S3MemesBucket:
    Description: Reference of the S3 MemesBucket from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  S3PicturesBucket:
    Description: Reference of the S3 PicturesBucket from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  S3ConfigurationBucket:
    Description: Reference of the S3 ConfigurationBucket from the SSM
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ApplicationPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: S3Memes
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:GetObject
                Resource:
                  - !Sub arn:aws:s3:::${S3MemesBucket}/*
                  - !Sub arn:aws:s3:::${S3MemesBucket}
              - Sid: S3Pictures
                Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource:
                  - !Sub arn:aws:s3:::${S3PicturesBucket}
                  - !Sub arn:aws:s3:::${S3PicturesBucket}/*
              - Sid: S3Configuration
                Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource:
                  - !Sub arn:aws:s3:::${S3ConfigurationBucket}
                  - !Sub arn:aws:s3:::${S3ConfigurationBucket}/*
              - Sid: GetSSMParams
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Project}/${Stage}/${Component}/*
              - Sid: GetSecretValue
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref DbAppCredentialsSecretArn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  InstanceRoleParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component} Instance Role
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/application-instance-role/name
      Value: !Ref InstanceRole
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-application-instance-role-name-param

Outputs:
  InstanceRole:
    Description: The instance role name
    Value: !Ref InstanceRole
  InstanceRoleParamName:
    Description: The name of the SSM parameter where the name of the instance role is stored
    Value: !Ref InstanceRoleParam
