AWSTemplateFormatVersion: 2010-09-09
Description: Template for s3 bucket

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Stage:
    Description: Stage name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  BucketFunction:
    Description: Name of the bucket
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${Component}-${BucketFunction}-bucket

  S3BucketNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${Project}-${Stage}-${Component}-${BucketFunction} S3 Bucket
      Tier: Standard
      Name: !Sub /${Project}/${Stage}/${Component}/${BucketFunction}-bucket/name
      Value: !Ref S3Bucket
      Tags:
        Name: !Sub ${Project}-${Stage}-${Component}-${BucketFunction}-name-param

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: S3 Bucket bucket name
  S3BucketParamName:
    Description: The name of the SSM parameter where the Name of the  Bucket is stored
    Value: !Ref S3BucketNameParam
